sudo: true
dist: trusty

language: python
python:
  "3.6"
cache: pip

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

install:
  - wget http://chromedriver.storage.googleapis.com/2.29/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - export PATH=$PATH:$(pwd)
  - chmod +x chromedriver
  - pip install -r requirements.txt
  - pip install coveralls codeclimate-test-reporter

before_script:
  - export PATH=$PATH:/usr/lib/chromium-browser/
  - python manage.py collectstatic --noinput

script:
  - coverage run manage.py test --verbosity=2

after_success:
  - coveralls
  - codeclimate-test-reporter

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
