language: python
python:
  "2.7"

before_install:
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

install:
  - pip install -r requirements.txt
  - pip install coveralls codeclimate-test-reporter

before_script:
  - python manage.py collectstatic --noinput

script:
  - coverage run manage.py test RIGS

after_success:
  - coveralls
  - codeclimate-test-reporter
